Outlier detect
UBC-MDS/Group_9_GA_Metrics pull request #20
Opened 2024-01-12 22:48 UTC by tangyl92

2024-01-12 22:51 UTC, tangyl92 commented
create function, Since I don't know the sample data distribution and not sure if I can detect the outlier. I change the function to find the best and worst market campaign in given data based on chosen metric.

2024-01-12 22:59 UTC, ianm99 requested changes
Docstring needs a little work.

2024-01-12 22:59 UTC, ianm99 commented on src/dscigametrics/metric4.py
> +    Analyzes marketing campaign performance over a specified date range and identifies the best and worst performing campaigns based on a selected metric.
initial blank line after """

2024-01-12 22:59 UTC, ianm99 commented on src/dscigametrics/metric4.py
> +    Parameters:
should insert a line like --------- under Parameters. Look at my docstring in compute_metrics.py

2024-01-12 22:59 UTC, ianm99 commented on src/dscigametrics/metric4.py
> +    Returns:
insert another ------- under Returns

2024-01-12 22:59 UTC, ianm99 commented on src/dscigametrics/metric4.py
> +    Example usage:
examples not needed for now

2024-01-12 22:59 UTC, ianm99 commented on src/dscigametrics/metric4.py
> +    """
blank line before the """

2024-01-12 22:59 UTC, ianm99 commented on src/dscigametrics/metric4.py
> +    df (pandas.DataFrame): A DataFrame containing campaign data. Expected to include columns for dates, campaign IDs, and various metrics like visits, transactions, and revenue.
delete second sentence for now

2024-01-12 22:59 UTC, ianm99 commented on src/dscigametrics/metric4.py
> +    metric (str): The name of the metric to be used for evaluating campaign performance. This should be one of the keys returned by the 'calculate_campaign_metrics' function, such as 'conversion_rate
delete second sentence for now. Your information presupposes facts not in evidence

2024-01-12 23:42 UTC, tangyl92 commented
done

2024-01-13 00:41 UTC, ianm99 approved these changes
thanks!

2024-01-13 01:08 UTC, WeilinHan8 requested changes
Please make the changes I listed in file

2024-01-13 01:08 UTC, WeilinHan8 commented on src/dscigametrics/metric4.py
> +
Only one blank line before ```

2024-01-13 01:08 UTC, WeilinHan8 commented on src/dscigametrics/metric4.py
> +        A dictionary containing two key-value pairs - 'best_campaign' and 'worst_campaign'. Each is a dictionary itself, containing the 'campaign_id' and its corresponding 'metrics', which include th
Please break the line manually, currently they are in one line and reader has to scroll to the far right to finish the sentence.

2024-01-13 01:08 UTC, WeilinHan8 commented on src/dscigametrics/metric4.py
> +        A DataFrame containing campaign data. Expected to include columns for dates, campaign IDs, and various metrics like visits, transactions, and revenue.
manually break this sentence to new line. Thanks

2024-01-13 01:08 UTC, WeilinHan8 commented on src/dscigametrics/metric4.py
> +        The name of the metric to be used for evaluating campaign performance. This should be one of the keys returned by the 'calculate_campaign_metrics' function, such as 'conversion_rate', 'total_
break the line manually so reader don't have to scroll to the right.

2024-01-13 01:08 UTC, WeilinHan8 commented on src/dscigametrics/metric4.py
> +def find_best_and_worst_campaigns(df, start_date, end_date, campaign_ids, metric):
please rename your file to your function name "find_best...." and make sure the old file was deleted.

2024-01-13 01:14 UTC, WeilinHan8 commented on src/dscigametrics/metric4.py
> +
Also add the four metrics description in here, you can copy from Ian's script (compute_metrics)

2024-01-13 02:30 UTC, tangyl92 commented
@WeilinHan8 I reject them all.

2024-01-13 02:30 UTC, closed without merging