build up test file and function
UBC-MDS/Group_9_GA_Metrics pull request #33
Opened 2024-01-18 23:28 UTC by tangyl92

Hi guys:

I build up my function and test file. In my branch, I also build the compute metrics function since it will be used in my part. Please use it as reference and when Ian finish his part, I will delete it.

I also build up a toy data set with Campaign ID transaction revenue being filled by filling in the random number. Feel free to check it. If you guys have any better idea, please let me know I will delete that one if necessary

Best.

2024-01-18 23:31 UTC, tangyl92 commented
The source code to build up the toy_data set is under toy_data.ipynb in src/; the module built.ipynb is for experiment to test the toy data actually works. compute_metrics_temp.py is my version of metrics built up. Please don't merge to the main. Just review and tell me what you prefer to change.

2024-01-18 23:38 UTC, tangyl92 commented
<img width="567" alt="截屏2024-01-18 15 37 42" src="https://github.com/UBC-MDS/Group_9_GA_Metrics/assets/143661842/bf291e04-c41a-429a-8dfb-5b0ed689d40c">

2024-01-19 02:07 UTC, beth-ouyang requested changes
Please change the file name `tests/test_dscigametrics.py` to `tests/test_find_campaigns.py` to align with the function name, thanks!

2024-01-19 02:10 UTC, beth-ouyang commented on src/dscigametrics/compute_metrics_temp.py
Is this file from @ianm99 and with some modification, or is this a whole new file by @tangyl92? 
Because I believe that Ian is also working on the same function. Just want to make sure that there's no duplicate jobs.

2024-01-19 02:21 UTC, ianm99 commented on src/dscigametrics/compute_metrics_temp.py
this is a completely new file i had no part in it

2024-01-19 02:35 UTC, tangyl92 commented on src/dscigametrics/compute_metrics_temp.py
No worries, I will clear up the things. Pls review it later

2024-01-19 05:28 UTC, tangyl92 commented
I have clear unnecessary thing and rebuild the function as well as test file. please check it

2024-01-19 05:31 UTC, tangyl92 commented
<img width="570" alt="截屏2024-01-18 21 25 09" src="https://github.com/UBC-MDS/Group_9_GA_Metrics/assets/143661842/41ba5f2d-5f22-42a3-a604-10bd50ccfd1b">

2024-01-19 20:16 UTC, beth-ouyang approved these changes
seems good now!

2024-01-19 20:16 UTC, beth-ouyang commented on tests/ga_metrics_test_data.csv
Because Github failed to show the difference of this file, I'm not sure what was the modification of the test data.
Did you change it (?)

2024-01-19 20:16 UTC, beth-ouyang commented on tests/ga_metrics_test_data.csv
Oops I got it, you did not change it, you just re-uploaded it?

2024-01-19 21:10 UTC, merged

2024-01-19 21:11 UTC, WeilinHan8 commented
Merged your branch! Please update your issue :)

2024-01-19 21:50 UTC, tangyl92 commented
Yes, I didn’t change it. I just reload it. The same one you guys use.


发自我的 iPhone

在 2024年1月19日，12:16，Beth Ou Yang ***@***.***> 写道：

﻿
[CAUTION: Non-UBC Email]

@beth-ouyang approved this pull request.

seems good now!

________________________________

On tests/ga_metrics_test_data.csv<https://github.com/UBC-MDS/Group_9_GA_Metrics/pull/33#discussion_r1458495518>:

Because Github failed to show the difference of this file, I'm not sure what was the modification of the test data.
Did you change it (?)

________________________________

On tests/ga_metrics_test_data.csv<https://github.com/UBC-MDS/Group_9_GA_Metrics/pull/33#discussion_r1458497320>:

Oops I got it, you did not change it, you just re-uploaded it?

—
Reply to this email directly, view it on GitHub<https://github.com/UBC-MDS/Group_9_GA_Metrics/pull/33#pullrequestreview-1831761237>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCIBWEWS3KRLMTJ2POH7CQDYPLIBDAVCNFSM6AAAAABCBCSNLKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMZRG43DCMRTG4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>