Adding function and test files
UBC-MDS/Group_9_GA_Metrics pull request #34
Opened 2024-01-19 00:03 UTC by WeilinHan8

Hi team,
I added my function content and test file for my function, Please kindly review them.

2024-01-19 07:25 UTC, beth-ouyang requested changes

2024-01-19 07:25 UTC, beth-ouyang commented on tests/test_dailyplot.py
It would be better to make the file name align with the function name, so maybe add an underscore!

2024-01-19 23:16 UTC, WeilinHan8 commented
@beth-ouyang  I have connected with Cindy (TA), she said considering the number of tests I have included in the test function and the nature of my function (creating a plot). The current test file is good enough

2024-01-19 23:29 UTC, beth-ouyang commented
ohh that's great!!! I will approve and merge !

2024-01-20 04:41 UTC, tangyl92 approved these changes

2024-01-20 05:51 UTC, beth-ouyang approved these changes
GOOOOD!!!

2024-01-20 05:51 UTC, merged